# Generated by Django 5.1.4 on 2024-12-18 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="rate",
            ),
        ),
    ]
