# Generated by Django 5.1.4 on 2024-12-16 18:29

import product_app.models.category
import product_app.models.product_image
import product_app.models.subcategory
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=product_app.models.category.category_image_directory_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=product_app.models.product_image.product_image_directory_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=product_app.models.subcategory.subcategory_image_directory_path,
                verbose_name="image",
            ),
        ),
    ]
