# Generated by Django 5.1.4 on 2024-12-15 18:07

import django.db.models.deletion
import product_app.models.product_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ("name",),
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="product_app.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=product_app.models.product_image.product_image_directory_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="product_app.category",
            ),
        ),
    ]
