# Generated by Django 5.1.4 on 2024-12-15 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_app",
            "0002_alter_category_options_alter_subcategory_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="archived"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="rate",
            ),
        ),
    ]
