# Generated by Django 5.1.4 on 2024-12-15 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0003_product_archived_alter_review_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="count",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="price",
            ),
            preserve_default=False,
        ),
    ]
