# Generated by Django 5.1.4 on 2024-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0003_review_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="review",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
