# Generated by Django 5.1.4 on 2024-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0004_alter_review_author_alter_review_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(verbose_name="created at"),
        ),
    ]
