# Generated by Django 5.1.4 on 2024-12-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0005_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date_from",
            field=models.DateField(verbose_name="start date"),
        ),
    ]
