# Generated by Django 5.1.4 on 2024-12-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0005_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
    ]
