# Generated by Django 5.1.4 on 2024-12-18 16:04

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0006_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="created at"
            ),
        ),
    ]
