# Generated by Django 5.1.4 on 2024-12-15 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0006_alter_sale_date_from"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "sale",
                "verbose_name_plural": "sales",
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
    ]
