# Generated by Django 5.1.4 on 2024-12-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0008_alter_review_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="created_at",
            new_name="date",
        ),
    ]
