# Generated by Django 5.1.4 on 2024-12-14 19:51

import auth_app.models.profile
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "surname",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="surname"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="patronymic"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=17, verbose_name="phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=auth_app.models.profile.avatar_directory_path,
                        verbose_name="avatar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
