# Generated by Django 5.1.4 on 2024-12-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="name"
            ),
        ),
    ]
