# Generated by Django 5.1.4 on 2024-12-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_profile_name_profile_patronymic_profile_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
