# Generated by Django 5.1.4 on 2024-12-12 10:10

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_alter_profile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=auth_app.models.avatar_directory_path,
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="patronymic",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="patronymic"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=17, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="surname",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="surname"
            ),
        ),
    ]
