# Generated by Django 5.1.4 on 2024-12-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0003_basket_session_id_alter_basket_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="session_id",
        ),
    ]
