# Generated by Django 5.1.4 on 2024-12-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0005_basket_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="session_id",
            field=models.CharField(default=None, null=True),
        ),
    ]
