# Generated by Django 5.1.4 on 2024-12-25 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0008_alter_basket_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="count",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="count",
            ),
        ),
    ]
