# Generated by Django 5.1.4 on 2024-12-26 11:17

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0010_basket_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="fixed_price",
            field=models.DecimalField(
                decimal_places=2,
                default=None,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(default=None, null=True)),
                (
                    "full_name",
                    models.CharField(default=None, null=True, verbose_name="full name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                ("phone", models.CharField(max_length=17, verbose_name="phone")),
                (
                    "delivery_type",
                    models.CharField(max_length=16, verbose_name="delivery type"),
                ),
                (
                    "payment_type",
                    models.CharField(max_length=16, verbose_name="payment type"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("status", models.CharField(max_length=16, verbose_name="status")),
                ("city", models.CharField(max_length=16, verbose_name="city")),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basket",
            name="order",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to="order_app.order",
            ),
        ),
    ]
