# Generated by Django 5.1.4 on 2024-12-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0012_alter_order_address_alter_order_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_cost",
        ),
    ]
